### ISSUE TITLE
Fuse NEON technology => https://neon-bindings.com/

### ISSUE THREAD

**Issue by usagi** [usagi/template-rust-backend-with-electron-frontend#3]
From reddit: https://www.reddit.com/r/rust/comments/flsoa0/templaterustbackendwithelectronfrontend_released/fl0dv4p/

![image](https://user-images.githubusercontent.com/115972/77165881-855a2d00-6af6-11ea-9e60-044abc8215f4.png)

**Comment by usagi** [comment]
NEON ecosystem seems to have some problems.

1. `neon new` could not be complete in Windows -> https://github.com/neon-bindings/neon/issues/406#issuecomment-601737636
    - note: Maybe, it is *not a critical problem* at least for `neon new` -> https://github.com/neon-bindings/neon/issues/406#issuecomment-601832883
        - parse arguments in `cli.ts` -> call into `cli_new.ts` -> STDIN requests -> main process (mkdir and make files) -> flavor outputs **(The problems is in the here)** -> exit(0)
        - `neon build --release` is work expectedly in the directory that is breaked `neon new` process used CTRL+C
2. `npm i neon-hello` could not be complete in Arch(WSL2) and Windows -> https://github.com/dherman/neon-hello/issues/2
    - note: The official instruction of `Basics/Electron Apps` required this package -> https://neon-bindings.com/docs/electron-apps

**Comment by usagi** [comment]
Maybe, I'll give up to use NEON then I create a new marsharing automation system if NEON ecosystem is not expected for me. My target is not NEON ecosystem inclusion and commiting that is prepare a simple and practicable project for Rust backend with react-electron based frontend.

-----

First, my motivation is not development for Electron frontend-ed project. It just the alternative choice for me. I want to use an ideal awesome frontend framework that  is high Rust purity and nearly idel perfect GUI Toolkit ecosystems such as .NET Core/WPF/Prism or Qt/QML with common business GUI parts and GPU 3D context and good default look'n feels! But, the ideal solution is not available in the real world at least now. And I have motivation for development to backend systems but I have not for frontend subsytems. I have not so much a life times.

Ofcourse, I know WPF/Prism is not perfect that is messy for use. I know Qt or Gtk bidings is available on Rust ecosystem but these expensive pricing or GPL/LGPL infective. And conrod is really awesome GUI Toolkit but it has not enough for business GUI parts and so cheap default looks(conrod is focused to game development then it is not a problem. In commonly, game project creates own originally look'n feels). And I really expecting to `druid` and `OrbTk` but these are so youth that has no availability for global language supportings and many common features. Therefore, I choosen Electron frontend for real efficient *just in now*.

**Comment by usagi** [comment]
https://github.com/dherman/neon-hello/network <- The original neon-hello

![image](https://user-images.githubusercontent.com/115972/77220047-3dcbb380-6b7f-11ea-81d7-5fee626e0797.png)

https://github.com/amilajack/neon-hello <- A maintein fork

**Comment by usagi** [comment]
💪 https://github.com/neon-bindings/website/pull/124 💪

**Comment by usagi** [comment]
Then, I restart the tutor: https://neon-bindings.com/docs/electron-apps

But, I got the next trouble with `npm run build` in https://neon-bindings.com/docs/electron-apps#thats-it section:

```
PS C:\Users\usagi\tmp\z\electron-quick-start> npm run build

> electron-quick-start@1.0.0 build C:\Users\usagi\tmp\z\electron-quick-start
> electron-build-env neon build neon-hello --release

neon ERR! spawn cargo ENOENT

Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
electron-build-env error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 build: `electron-build-env neon build neon-hello --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\usagi\AppData\Roaming\npm-cache\_logs\2020-03-21T08_53_49_427Z-debug.log
```

- https://github.com/dherman/electron-build-env

Ah... @dherman's repos again. Maybe the repository has not been maintained for years. And, it will be no response if someone reporting the situation to Issues or pull-req. Sigh... I'm tired, what is the "quick".

**Comment by usagi** [comment]
Perhaps even when integrating NEON into this repos, it is faster and easy to integrating myself originally method without a trial to the "quick" guide in NEON official docs and unmaintained related repos. Thus, I give up to use the "quick" guide and related repos works.

**Comment by usagi** [comment]
Next step: I'll try to integrating NEON into this repos using my own method.

**Comment by usagi** [comment]
💪 https://github.com/neon-bindings/neon/pull/501 💪

**Comment by usagi** [comment]
I'm studying NEON now. I want to fuse NEON into this template project but I don't want to lost cdylib level architective independency. Please wait more a hours or a few days, I know some experts has a good tips maybe but I need more a few internal knowledge of NEON.

**Comment by usagi** [comment]
Maybe, these examples is helpful for this issue:

- https://github.com/neon-bindings/examples
    - Example-20 `workspace`: https://github.com/neon-bindings/examples/tree/master/workspace
    - Example-18 `publising modules`: https://github.com/amilajack/disk-utility

**Comment by usagi** [comment]
Note: In now, this issue is staking. I was integrated neon experimentaly but it was not work. The runtime said `Error: Module did not self-register.` from `reuiqre('../native/index.node')`. JS is really .... sigh.

**Comment by usagi** [comment]
note: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by usagi** [comment]
note: https://github.com/neon-bindings/neon-cli/issues/36

**Comment by usagi** [comment]
note: https://github.com/electron/electron/issues/18397

**Comment by usagi** [comment]
note: https://github.com/electron/electron/pull/21287

**Comment by usagi** [comment]
I got it.

![image](https://user-images.githubusercontent.com/115972/77915076-d37ae780-72d1-11ea-886a-f6e7051d8845.png)

I'll itegrate `NEON` to this template soon, maybe.

**Comment by usagi** [comment]
`NEON` vs. `node-ffi-napi` -> https://github.com/usagi/neon-vs-node-ffi-napi#a-result

**Comment by usagi** [comment]
NEON integrated version works fine:

![image](https://user-images.githubusercontent.com/115972/77974097-20da7180-7331-11ea-88d6-81a6b30afdb8.png)

and refactoring `scripts` in `package.json`:

![image](https://user-images.githubusercontent.com/115972/77974308-b1b14d00-7331-11ea-93c7-7617280c6fb7.png)

👍✨

**Comment by usagi** [comment]
Plan: 

1. Push the NEON version to `experimental` branch
2. Test `cargo generate` with the `experimental` branch
3. Branch the node-ffi-napi version to the `node-ffi-napi` branch based the `master` branch
4. Test `cargo generate` with the `node-ffi-napi` branch
5. Merge the `experimental` branch to the `master` branch
6. Test `cargo generate` with the `master` branch

**Comment by usagi** [comment]
The NEON version works well in the `experimental` branch now. ✨

![image](https://user-images.githubusercontent.com/115972/78053015-ed442980-73ba-11ea-92c6-6c38174bc3c3.png)

👍

**Comment by usagi** [comment]
Well, done! #5
